const imgBig =[
  './img/comic/01.jpg',
  './img/comic/02.jpg',
  './img/comic/03.jpg',
  './img/comic/04.jpg',
  './img/comic/05.jpg',
  './img/comic/06.jpg',
  './img/comic/07.jpg',
  './img/comic/08.jpg',
  './img/comic/09.jpg',
  './img/comic/10.jpg',
  './img/comic/11.jpg',
  './img/comic/12.jpg',
]
const imgLittle =[
  './img/comic/01.jpg',
  './img/comic/02.jpg',
  './img/comic/03.jpg',
  './img/comic/04.jpg',
  './img/comic/05.jpg',
  './img/comic/06.jpg',
  './img/comic/07.jpg',
  './img/comic/08.jpg',
  './img/comic/09.jpg',
  './img/comic/10.jpg',
  './img/comic/11.jpg',
  './img/comic/12.jpg',
]
